# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ujlJB1R2ymkohPKTeiwIjYuUTEyZB5bm

# New Section
"""

n=int(input(""))
if(n>2 and n%2==0):
  print("yes")
else:
  print("no")