# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ujlJB1R2ymkohPKTeiwIjYuUTEyZB5bm

# New Section
"""

n=str(input(""))
length=len(n)
if(length<10):
  print(n)
else:
  print(n[0],(length-2),n[-1])
